language: generic

# Use the trusty environment, since the netcdf packages in 12.04 are broken
dist: trusty
sudo: required

env:
  global:
    MPI_IMPL=openmpi

  matrix:
    - GFORTRAN_VERSION=trusty
    - GFORTRAN_VERSION=4.8
    - GFORTRAN_VERSION=4.9
    - GFORTRAN_VERSION=5 
    - GFORTRAN_VERSION=6


before_install:
  - export TRAVIS_ROOT=$HOME/local
  - mkdir -p $TRAVIS_ROOT/bin
  - export PATH="$TRAVIS_ROOT/bin:$PATH"
  # Install Git LFS
  #- ./TRAVIS/install_gitlfs.sh $TRAVIS_ROOT

  # Install requirements for M.C. Kernel
  - |
    if [[ "$GFORTRAN_VERSION" == "trusty" ]]; then 
      sudo apt-get update -qq
      sudo apt-get install -qq gfortran libnetcdff5 libnetcdf-dev libfftw3-dev openmpi-bin libopenmpi-dev
    else
      sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      sudo -E apt-get -yq update &>> ~/apt-get-update.log
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gfortran-$GFORTRAN_VERSION g++-$GFORTRAN_VERSION
    # Install OpenMPI
      ./TRAVIS/install_mpi.sh $TRAVIS_ROOT $MPI_IMPL $GFORTRAN_VERSION
    # Get and install FFTW3
      ./TRAVIS/install_fftw.sh $TRAVIS_ROOT $GFORTRAN_VERSION
    # Get and install NetCDF4
      ./TRAVIS/install_netcdf.sh $TRAVIS_ROOT $GFORTRAN_VERSION
    fi

  - pip install --user cpp-coveralls
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran libnetcdff5 libnetcdf-dev libfftw3-dev openmpi-bin libopenmpi-dev
  # # Get test wavefields (2GB, takes some time)
  # - wget https://www.geophysik.uni-muenchen.de/~staehler/kerner_wavefields.tar.bz2
  # - tar -xvf kerner_wavefields.tar.bz2
  # - git lfs pull
  # - |
  #   cd tests/reference_solutions 
  #   tar -xvf test_nonmerged.tar
  #   tar -xvf test_merged.tar
  #   cd -

install:
  #- ./copy_templates.sh
  #- git clone https://sstaehler/axisem_nightly_tests
- which mpif90
- mpif90 -show
- mpif90 -v
- sh -c 'sed -i -e "s/NETCDF_PATH = /NETCDF_PATH = $(TRAVIS_ROOT) \#/g" make_mc_kernel.macros'
- make -j

script:
- echo 'Unit tests...' && echo -en 'travis_fold:start:script.1\\r'
  #- |
  #  make check
  #cat tests/mckernel_tests.log
  - echo -en 'travis_fold:end:script.1\\r'
  # - echo 'Test make_kerner_input.py...' && echo -en 'travis_fold:start:script.2\\r'
  # - ./UTILS/make_kerner_input.py --nfilter 4 --f0 50 --noplot
  # - diff receiver.dat tests/ref_make_input/receiver.dat
  # - diff CMTSOLUTION tests/ref_make_input/CMTSOLUTION
  # - diff filters.dat tests/ref_make_input/filters.dat
  # - echo -en 'travis_fold:end:script.2\\r'
  # - echo 'Test run on nonmerged wavefield files...' && echo -en 'travis_fold:start:script.3\\r'
  # - ./submit.py -n 2 --fwd_dir wavefield/fwd/ --bwd_dir wavefield/bwd/ -q foreground --allowed_error 1e-16 --no_int_over_volume test_nonmerged
  #   #- ./tests/compare_results.py test_nonmerged
  # - echo -en 'travis_fold:end:script.3\\r'
  # - echo 'Test run on merged wavefield files...' && echo -en 'travis_fold:start:script.4\\r'
  # - ./submit.py -n 2 --fwd_dir wavefield/fwd_merged/ --bwd_dir wavefield/bwd_merged/ -q foreground --allowed_error 1e-16 --no_int_over_volume test_merged
  #   #- ./tests/compare_results.py test_merged
  # - echo -en 'travis_fold:end:script.4\\r'

after_success:
- coveralls --gcov-options '\-lp'

cache:
  directories:
    - $HOME/local
    - $HOME/wavefield
