language: generic

# Use the trusty environment, since the netcdf packages in 12.04 are broken
dist: trusty
sudo: required

env:
  global:
    MPI_IMPL=openmpi

  matrix:
    - GFORTRAN_VERSION=4.7
    - GFORTRAN_VERSION=4.8
    - GFORTRAN_VERSION=4.9
    - GFORTRAN_VERSION=5 
    - GFORTRAN_VERSION=6
    - GFORTRAN_VERSION=4.8
      EXTRAFLAGS=-fopenmp
    - GFORTRAN_VERSION=6
      EXTRAFLAGS=-fopenmp

before_install:
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  # Install conda only if necessary
  - command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
     bash miniconda.sh -b -f -p $MINICONDA; }
  - conda update --yes conda
  - conda remove --yes -n condaenv --all || echo "Conda not yet installed"
  - conda create --yes -n condaenv python=2.7
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes -c obspy obspy # python=2.7
  - travis_retry pip install $PIP_DEPS
   #Install Gfortran in selected version
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install 
    gfortran-$GFORTRAN_VERSION g++-$GFORTRAN_VERSION tcsh gnuplot
  - export TRAVIS_ROOT=$HOME/travis
    #- mkdir -p $TRAVIS_ROOT
  - wget https://www.geophysik.uni-muenchen.de/~staehler/mpi_builds/mpi_netcdf_gcc$GFORTRAN_VERSION.tar.gz 
  - tar -xf mpi_netcdf_gcc$GFORTRAN_VERSION.tar.gz -C $HOME
  # Get and install OpenMPI
  # - ./TRAVIS/install_mpi.sh $TRAVIS_ROOT $MPI_IMPL $GFORTRAN_VERSION > LOG_OpenMPI.log
  # Get and install NetCDF4
  #- ./TRAVIS/install_netcdf.sh $TRAVIS_ROOT $GFORTRAN_VERSION > LOG_NetCDF4.log
  - export PATH="$TRAVIS_ROOT/bin:$PATH"

install: true
  
script:
  - cd TESTING;
  - python test_nightly_axisem.py -t 1
  - python test_nightly_axisem.py -t 2
  - python test_nightly_axisem.py -t 3

after_success:

cache:
  apt: true

  directories:
    #- $HOME/travis
    - $HOME/miniconda
