language: generic

# Use the trusty environment, since the netcdf packages in 12.04 are broken
dist: trusty
sudo: required

env:
  global:
    MPI_IMPL=openmpi

  matrix:
    - GFORTRAN_VERSION=4.8
    - GFORTRAN_VERSION=4.9
    - GFORTRAN_VERSION=5 
    - GFORTRAN_VERSION=6

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - gfortran-4.8
#       - gfortran-4.9
#       - gfortran-5
#       - gfortran-6
#       - g++-4.8
#       - g++-4.9
#       - g++-5
#       - g++-6

before_install:
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  # Install conda only if necessary
  - command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
     bash miniconda.sh -b -f -p $MINICONDA; }
  - conda update --yes conda
    #- conda remove --yes -n condaenv --all
  - conda create --yes -n condaenv python=2.7
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes -c obspy python=2.7
  - travis_retry pip install $PIP_DEPS
   #Install Gfortran in selected version
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install 
    gfortran-$GFORTRAN_VERSION g++-$GFORTRAN_VERSION
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir -p $TRAVIS_ROOT
  # Get and install OpenMPI
  - ./TRAVIS/install_mpi.sh $TRAVIS_ROOT $MPI_IMPL $GFORTRAN_VERSION
  # Get and install FFTW3
  - ./TRAVIS/install_fftw.sh $TRAVIS_ROOT $GFORTRAN_VERSION
  # Get and install NetCDF4
  - ./TRAVIS/install_netcdf.sh $TRAVIS_ROOT $GFORTRAN_VERSION

install:
  #- gfortran-$GFORTRAN_VERSION -v
  #- gfortran-$GFORTRAN_VERSION hello_world.f90 -o hello_world.x
  - cd TESTING
    python2.7 test_nightly_axisem.py -t 1

script:
  - ./hello_world.x

after_success:

cache:
  apt: true

  directories:
    - $HOME/travis
    - $HOME/miniconda
